FROM golang:1.24-alpine

WORKDIR /app

RUN apk update && apk add --no-cache git curl

RUN go install github.com/air-verse/air@latest

COPY ./backend/go.mod ./backend/go.sum ./
RUN go mod download

COPY ./backend .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]


# FROM golang:1.20

# WORKDIR /app

# COPY ./backend/go.mod .

# RUN go mod tidy

# RUN go mod download

# COPY ./backend .

# WORKDIR /app/cmd/server

# RUN go build -o /app/build/server server.go

# EXPOSE 8080

# CMD ["/app/build/server"]