
import { ReduxProvider } from '@/store/redux-provider'
import './globals.css'

import type { Metadata } from 'next'
import AuthWrapper from '@/wrappers/auth-wrapper'
import { ReactNode } from 'react'
import StoreLoader from '@/components/store-loader'
import StoreModal from '@/components/store-modal'

export const metadata: Metadata = {
  title: 'Apptimus home assignment',
  description: 'Generated by Shaked Golan',
}

interface ChildrenProps {
  children: ReactNode;
}
export default function RootLayout({
  children,
}: ChildrenProps) {

  return (


    <html lang="en" className=' min-h-screen max-h-max' suppressHydrationWarning>
      <body>
        <ReduxProvider>
          <MainLayout>
            <AuthWrapper>
              <StoreLoader />
              <StoreModal />
              {children}
            </AuthWrapper>
          </MainLayout>
        </ReduxProvider>
      </body>
    </html>

  )
}

function MainLayout({ children }: ChildrenProps) {
  return (
    <main
      className="min-h-screen bg-base-100 grid 
                grid-cols-[100px_1fr_100px]
                tablet:grid-cols-[50px_1fr_50px] tablet:px-12  
                mobile:grid-cols-1 mobile:px-4 pt-28"
    >
      <div className="col-span-1"></div>
      <div className="col-span-1">{children}</div> {/* Content */}
      <div className="col-span-1"></div>
    </main>
  );
}
